### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by Andy79881** [owntech-foundation/SPIN#1]
Actually, where can i find source Code for the Firmware? Furthermore  I would  like  to port to another Stm32 Controller. Could you give some advice?

**Comment by jalinei** [comment]
We are still in the process of mirroring it properly to GitHub. For now you can find the sources at the link below. 
https://gitlab.laas.fr/owntech/power-api/core
The API largely relies on special hardware peripherals that not all STM32 families are supporting. Can you be more specific on the part reference you were thinking of ?

**Comment by Andy79881** [comment]
It would be the Stm32L051 Device. Nevertheless, a list of supported devices would be helpful.
